In [1]:
import pandas as pd
import numpy as np
from sklearn import preprocessing
import matplotlib.pyplot as plt 
plt.rc("font", size=14)
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
import seaborn as sns
sns.set(style="white")
sns.set(style="whitegrid", color_codes=True)

In [2]:
df=pd.read_csv(r"C:\Users\yash3.goyal\Desktop\train.csv")

In [3]:
x=df.drop(['ID_code','target'],axis=1)
y=df.target

In [4]:
x_train, x_test, y_train, y_test = train_test_split(x, y,test_size=0.3)

In [9]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=100, random_state=2019, verbose=1,
                                      class_weight='balanced', max_features = 0.5, 
                                       min_samples_leaf = 100)


rf.fit(x_train, y_train)

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done 100 out of 100 | elapsed: 51.4min finished


RandomForestClassifier(bootstrap=True, class_weight='balanced',
            criterion='gini', max_depth=None, max_features=0.5,
            max_leaf_nodes=None, min_impurity_decrease=0.0,
            min_impurity_split=None, min_samples_leaf=100,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            n_estimators=100, n_jobs=None, oob_score=False,
            random_state=2019, verbose=1, warm_start=False)

In [10]:
y_pred = rf.predict(x_test)
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y_test, y_pred)
print(confusion_matrix)

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


[[46601  7360]
 [ 3013  3026]]


[Parallel(n_jobs=1)]: Done 100 out of 100 | elapsed:    2.5s finished


In [11]:
from sklearn import metrics

print(metrics.accuracy_score(y_test, y_pred))

0.8271166666666666


In [12]:
from sklearn import metrics

print(metrics.roc_auc_score(y_test, y_pred))

0.6823407667437098


In [5]:
from sklearn.feature_selection import VarianceThreshold


feature_selector = VarianceThreshold(threshold=0)

# Fit finds the features with zero variance
feature_selector.fit(x_train)

VarianceThreshold(threshold=0)

In [6]:
feature_selector.get_support()

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,

In [7]:
sum(feature_selector.get_support())

200

In [8]:
data_t = x_train.T
data_t.head()

152048   192813   34257    74563    143031   159571   69155    199128  \
var_0   8.4295  12.2961   5.7353  13.9203  12.0783  13.0586   7.6813  10.5278   
var_1  -9.3537  -5.5811  -5.3532  -2.0235  -1.8267  -2.7102   1.9431   1.1185   
var_2  10.8130   8.6393   8.2503  17.5548  10.0182   9.6392   7.4778  14.0492   
var_3   6.7166   8.2139   5.4615   7.6281   8.9732   2.5103   6.1294   4.6953   
var_4  12.1462  11.6357  12.6408  13.7481  14.3851   8.7735  11.3018   8.9322   

        86222    173282   ...      185710   5976     110946   70223    86955   \
var_0  13.7614   9.8876   ...     10.4279  12.4616   9.9498   9.2127   8.4996   
var_1   0.0168   3.6419   ...      0.6765  -5.0196  -3.3498  -4.7928   1.5151   
var_2   8.7423   9.5288   ...     10.5321  10.1896  11.2391   7.7137  13.5783   
var_3   6.5488   6.0492   ...      6.2548   9.7007   4.8127   7.9419   6.9679   
var_4  12.9220  11.6381   ...      9.1555   8.8660  12.3222  13.0748  11.4431   

        172635   8672     149541   42180    193492  
var_0  10.0417  12.6345  12.1704   3.5881  12.0238  
var_1   2.1508  -6.1396  -1.9528  -6.0646  -1.9690  
var_2  13.3998   9.0656  14.0325  14.2913  12.8555  
var_3  10.1150   9.3740   5.8994   4.3901   7.9143  
var_4  10.7844   9.9936  13.6158   9.2953   9.8318  

[5 rows x 140000 columns]

In [9]:
data_t.duplicated().sum()

0

In [10]:
data_t[data_t.duplicated()]

KeyboardInterrupt: 

In [11]:
from sklearn.feature_selection import mutual_info_classif, mutual_info_regression
from sklearn.feature_selection import SelectKBest, SelectPercentile

In [12]:
mutual_info = mutual_info_classif(x_train.fillna(0), y_train)
mutual_info

array([2.02495133e-03, 2.05848255e-03, 2.50998549e-03, 1.00061171e-03,
       0.00000000e+00, 1.29185943e-03, 3.41811195e-03, 0.00000000e+00,
       9.95484618e-04, 2.32334790e-03, 1.11643869e-04, 0.00000000e+00,
       4.57415415e-03, 1.52506553e-03, 0.00000000e+00, 2.47539034e-03,
       1.20500510e-03, 0.00000000e+00, 9.74668841e-04, 2.74629169e-04,
       4.75146580e-05, 1.97747102e-03, 2.22718797e-03, 0.00000000e+00,
       3.50866903e-04, 1.51419451e-03, 3.40170489e-03, 9.38859477e-04,
       0.00000000e+00, 7.79990446e-04, 0.00000000e+00, 5.87562169e-04,
       1.53994252e-03, 6.66714987e-04, 1.32885094e-03, 1.58251306e-03,
       0.00000000e+00, 4.01541863e-04, 0.00000000e+00, 2.59212024e-04,
       2.40795474e-03, 1.07141841e-03, 4.29711937e-05, 0.00000000e+00,
       1.81748644e-03, 6.08254297e-04, 0.00000000e+00, 6.26880337e-04,
       8.65340011e-04, 3.44400484e-04, 0.00000000e+00, 9.34917799e-04,
       0.00000000e+00, 2.37454777e-03, 2.07497945e-04, 1.38356458e-03,
      

In [14]:
mi_series = pd.Series(mutual_info)
mi_series.index = x_train.columns
mi_series.sort_values(ascending=False)

var_12     0.004574
var_80     0.003860
var_139    0.003702
var_81     0.003642
var_6      0.003418
var_146    0.003415
var_26     0.003402
var_133    0.003023
var_110    0.002963
var_166    0.002961
var_99     0.002803
var_2      0.002510
var_15     0.002475
var_108    0.002460
var_40     0.002408
var_177    0.002395
var_53     0.002375
var_190    0.002371
var_118    0.002354
var_9      0.002323
var_198    0.002289
var_174    0.002272
var_76     0.002232
var_22     0.002227
var_165    0.002198
var_164    0.002159
var_148    0.002123
var_1      0.002058
var_94     0.002054
var_92     0.002041
             ...   
var_30     0.000000
var_136    0.000000
var_66     0.000000
var_58     0.000000
var_57     0.000000
var_61     0.000000
var_178    0.000000
var_64     0.000000
var_187    0.000000
var_52     0.000000
var_114    0.000000
var_50     0.000000
var_65     0.000000
var_176    0.000000
var_46     0.000000
var_68     0.000000
var_59     0.000000
var_43     0.000000
var_69     0.000000


In [15]:
k_best_features = SelectKBest(mutual_info_classif, k=10).fit(x_train.fillna(0), y_train)
print('Selected top 10 features: {}'.format(x_train.columns[k_best_features.get_support()]))

Selected top 10 features: Index(['var_12', 'var_26', 'var_53', 'var_80', 'var_81', 'var_110', 'var_133',
       'var_139', 'var_146', 'var_190'],
      dtype='object')
